### ISSUE TITLE
`cc` and `conj`order

### ISSUE THREAD

**Issue by GPPassos** [UniversalDependencies/UD_English-EWT#49]
Using a parser trained in UD English 2.1 I have noticed a lot of constructions of the form "C X Y" (in this order), with
`conj(Y, X)`
`cc(X,C)`

This seemed strange to me as the usual order in English is "X C Y" (X and Y, X or Y...).

Using [Grew](http://talc2.loria.fr/grew/#) I have found 31 occurences of this and, analyzing some, they seem to be wrong.

Examples:

1. "around" should be `conj`of "in", I believe.

```
# sent_id = newsgroup-groups.google.com_DungeonsDragonsChillicotheOH45601_022e6f4a0cd6fb61_ENG_20050829_233300-0001
# text = I am looking for people who would like to play D&D 3.5 and live in or around the Chillicothe, OH area.
16	live	live	VERB	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	8	conj	8:conj	_
17	in	in	ADP	IN	_	24	case	24:case	_
18	or	or	CCONJ	CC	_	19	cc	19:cc	_
19	around	around	ADP	IN	_	24	conj	24:conj	_
...
24	area	area	NOUN	NN	Number=Sing	16	obl	16:obl	SpaceAfter=No
``` 

2.  "a" should be `det` of "half"
```
# sent_id = weblog-blogspot.com_alaindewitt_20060924104100_ENG_20060924_104100-0211
# text = Now that Afghanistan, Iraq and Libya are out, two and a half terrorist states remain: Iran, Syria and Lebanon, the latter being a Syrian colony.
11	two	two	NUM	CD	NumType=Card	14	compound	14:compound	_
12	and	and	CCONJ	CC	_	13	cc	13:cc	_
13	a	a	DET	DT	Definite=Ind|PronType=Art	14	conj	14:conj	_
14	half	half	NOUN	NN	Number=Sing	16	nummod	16:nummod	_
```

3. It seems to me that it should be `advmod(may-4,not-5)` and `conj(may-2,may-4)`.
```
# sent_id = answers-20111108101906AA2JJqq_ans-0003
# text = There may or may not be snow, depending on local weather conditions.
2	may	may	AUX	MD	VerbForm=Fin	6	aux	6:aux	_
3	or	or	CCONJ	CC	_	4	cc	4:cc	_
4	may	may	AUX	MD	VerbForm=Fin	6	conj	6:conj	_
5	not	not	PART	RB	_	6	advmod	6:advmod	_
6	be	be	VERB	VB	VerbForm=Inf	0	root	0:root	_
```

Thank you.

**Comment by nschneid** [comment]
Good points. Can you submit a pull request against the dev branch, fixing these errors in the source document files under not-to-release/sources?

**Comment by bguil** [comment]
It may help to give the Grew pattern to reproduce the search:

```
pattern {
  X -[cc]-> AND ;
  Y -[conj]-> X ;
  AND << X ;
  X << Y ;
}
```
@GPPassos, note that it is also possible to use the "Save" button to get a direct URL to the result of your search. For instance:
http://grew.loria.fr/search?custom=5a58732453a91&corpus=UD_English-2.1

**Comment by sebschu** [comment]
Yes, these definitely look like annotation errors.  It would be great if you could submit a pull request, as Nathan suggested. Otherwise I'll try to fix them for the next release.

**Comment by nschneid** [comment]
Based on [this query](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Econj%40L%20_&db=UD_English-dev&case_sensitive=False&hits_per_page=100) it looks like there are 37 instances of `conj` going from right to left. As far as I can tell they are all errors.

**Comment by sebschu** [comment]
Fixed in pull request #50 by @nschneid. Thanks!!!

**Comment by nschneid** [comment]
#50 doesn't fix all of these, just the coordinated prepositions.

**Comment by nschneid** [comment]
Confirmed that `conj` is now always left-to-right and none of the example errors in the original post remain.
